"""
==============================================================================
Subphase 1.3 — Celery Task Definitions & Job State Machine
3D-GAN Generation System

File        : tasks.py

State machine (stored in Celery result backend via Redis DB 1):

    QUEUED ──► PROCESSING ──► COMPLETED
                    │
                    ├──► FAILED     (exception, OOM, or INFERENCE_TIMEOUT)
                    └──► EXPIRED    (set by Beat purge task after 24h TTL)

Progress milestones emitted via self.update_state() during PROCESSING:
    30%  — post-forward-pass   (GPU work complete, scalar field on CPU)
    80%  — post-mesh-cleanup   (Marching Cubes + component filter done)
    100% — COMPLETED           (GLB written atomically to /outputs/)

Interconnection with Subphase 1.2 (inference.py):
    - run_inference() is imported and called directly.
    - Model singleton caching (load_models) is handled inside inference.py;
      because worker_concurrency=1, the cache is populated once per worker
      process lifetime and never re-loaded.
    - OUTPUTS_DIR is read from inference.py to keep paths consistent.

Interconnection with Subphase 1.4 (FastAPI):
    - Job ID (UUID) is generated by FastAPI POST /v1/generate and passed
      as the task ID to apply_async(task_id=job_id).
    - FastAPI GET /v1/jobs/{id} reads state via AsyncResult(job_id).
    - Redis key  gan3d:job:<job_id>:meta  stores submitted_at and error
      payload for the full Phase 1.4 response schema.

Error codes surfaced to FastAPI:
    INFERENCE_TIMEOUT   — SoftTimeLimitExceeded (task exceeded 100s)
    OOM_ERROR           — CUDA out-of-memory
    MESH_EXPORT_FAILED  — GLB write/rename failure
    UNKNOWN             — any other unhandled exception
==============================================================================
"""

from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path
from typing import Optional

import torch
from celery import Task
from celery.exceptions import SoftTimeLimitExceeded
from celery.utils.log import get_task_logger

import redis as _redis_lib

from celery_app import celery_app

# Standalone Redis client for task metadata — avoids circular import
# (celery_app cannot import tasks because tasks imports celery_app)
redis_client = _redis_lib.Redis(
    host=os.getenv("REDIS_HOST", "localhost"),
    port=int(os.getenv("REDIS_PORT", 6379)),
    db=int(os.getenv("REDIS_DB_BACKEND", 1)),
    decode_responses=True,
)

# Subphase 1.2 inference pipeline
from inference import run_inference, load_models, OUTPUTS_DIR

logger = get_task_logger(__name__)

# --------------------------------------------------------------------------- #
# Redis metadata helpers                                                       #
# TTL on metadata keys matches Celery result_expires (24h = 86400s)           #
# --------------------------------------------------------------------------- #
_META_TTL = 86400  # seconds


def _meta_key(job_id: str) -> str:
    return f"gan3d:job:{job_id}:meta"


def _write_meta(job_id: str, **fields):
    """Merge fields into the job metadata hash in Redis."""
    key = _meta_key(job_id)
    # Using pipeline + individual hset calls for compatibility with Redis 3.x
    pipe = redis_client.pipeline()
    for k, v in fields.items():
        pipe.hset(key, k, json.dumps(v))
    pipe.expire(key, _META_TTL)
    pipe.execute()


def read_job_meta(job_id: str) -> dict:
    """
    Read all metadata for a job.
    Called by FastAPI GET /v1/jobs/{id} to enrich the response payload.
    Returns an empty dict if the key has expired or never existed.
    """
    raw = redis_client.hgetall(_meta_key(job_id))
    return {k: json.loads(v) for k, v in raw.items()}


# --------------------------------------------------------------------------- #
# Base task class — warm up the GPU on first task in this worker process      #
# --------------------------------------------------------------------------- #
class GANBaseTask(Task):
    """
    Custom base task class.
    Calls load_models() on first execution so the singleton is cached before
    the first real job arrives. On workers with worker_concurrency=1 this
    fires exactly once per process lifetime.
    """
    abstract = True
    _device: Optional[torch.device] = None

    @property
    def device(self) -> torch.device:
        if self._device is None:
            self._device = torch.device(
                "cuda" if torch.cuda.is_available() else "cpu"
            )
        return self._device

    def on_failure(self, exc, task_id, args, kwargs, einfo):
        """Ensure VRAM is released on any unhandled failure path."""
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            logger.warning(
                "on_failure: torch.cuda.empty_cache() called for job %s", task_id
            )
        super().on_failure(exc, task_id, args, kwargs, einfo)


# --------------------------------------------------------------------------- #
# Error payload builder                                                        #
# --------------------------------------------------------------------------- #
_ERROR_CODE_MAP = {
    "SoftTimeLimitExceeded": "INFERENCE_TIMEOUT",
    "OutOfMemoryError":      "OOM_ERROR",
    "RuntimeError":          "MESH_EXPORT_FAILED",
}


def _build_error_payload(exc: Exception) -> dict:
    exc_type = type(exc).__name__
    code = _ERROR_CODE_MAP.get(exc_type, "UNKNOWN")

    # Specialise RuntimeError — only MESH_EXPORT_FAILED if message matches
    if isinstance(exc, RuntimeError):
        msg = str(exc)
        if "atomic_write_glb" in msg or "GLB" in msg or "exporter" in msg:
            code = "MESH_EXPORT_FAILED"
        elif "cuda" in msg.lower() or "out of memory" in msg.lower():
            code = "OOM_ERROR"
        else:
            code = "UNKNOWN"

    return {
        "code":    code,
        "message": str(exc)[:512],   # truncate — stored in Redis
    }


# --------------------------------------------------------------------------- #
# Primary generation task                                                      #
# --------------------------------------------------------------------------- #
@celery_app.task(
    bind=True,
    base=GANBaseTask,
    name="tasks.generate_3d_asset",
    queue="gan3d.generate",
    max_retries=0,              # never retry GPU tasks — deterministic failure
    track_started=True,         # emit STARTED state immediately on pickup
    ignore_result=False,
)
def generate_3d_asset(
    self,
    job_id:         str,
    image_data:     list,       # flat float list — JSON-serialisable form of
                                # the (1,3,H,W) tensor; rebuilt inside task
    image_shape:    list,       # [1, 3, H, W]
    noise_seed:     Optional[int] = None,
    mc_resolution:  int = 128,
    export_format:  str = "glb",
    skin_removal_layers: int = 0,
) -> dict:
    """
    Full 2D→3D generation task.

    Parameters (all JSON-serialisable — Celery constraint)
    -------------------------------------------------------
    job_id        : UUID string from FastAPI POST /v1/generate
    image_data    : flattened float32 tensor values (list of floats)
    image_shape   : [1, 3, H, W] — shape to reconstruct the tensor
    noise_seed    : optional int for reproducible noise sampling
    mc_resolution : Marching Cubes grid resolution (default 128)

    Returns (Phase 1.4 contract — stored in Celery result backend)
    --------------------------------------------------------------
    {
        "asset_url":        "/outputs/<job_id>.glb",
        "file_size_bytes":  int,
        "metadata":         { ...from inference.py... }
    }

    State transitions emitted
    -------------------------
    QUEUED      — set on task dispatch by FastAPI (before this function runs)
    PROCESSING  — set immediately on entry (track_started=True)
    30%         — after GPU forward pass
    80%         — after mesh cleanup
    COMPLETED   — on success (Celery sets this automatically on return)
    FAILED      — on any exception path
    """

    wall_start = time.perf_counter()

    # ---------------------------------------------------------------------- #
    # Record submission timestamp for TTL purge task                         #
    # ---------------------------------------------------------------------- #
    _write_meta(job_id, submitted_at=time.time(), mc_resolution=mc_resolution, skin_removal_layers=skin_removal_layers)

    logger.info(
        "generate_3d_asset START | job=%s | resolution=%d | seed=%s",
        job_id, mc_resolution, noise_seed,
    )

    # ---------------------------------------------------------------------- #
    # MILESTONE 0 — task is PROCESSING (Celery sets STARTED via track_started)
    # Emit an explicit state so FastAPI can surface a progress bar from tick 1
    # ---------------------------------------------------------------------- #
    self.update_state(
        state="PROGRESS",
        meta={
            "progress":  5,
            "stage":     "Initialising inference pipeline",
            "job_id":    job_id,
        },
    )

    try:
        # ------------------------------------------------------------------ #
        # Step 1 — Rebuild input tensor from JSON-safe list                  #
        # ------------------------------------------------------------------ #
        import numpy as np

        image_np = np.array(image_data, dtype=np.float32).reshape(image_shape)
        input_tensor = torch.from_numpy(image_np)   # still on CPU

        noise_vector = None
        if noise_seed is not None:
            rng = torch.Generator()
            rng.manual_seed(noise_seed)
            from inference import LATENT_DIM
            noise_vector = torch.randn(
                1, LATENT_DIM, generator=rng, dtype=torch.float32
            )

        # ------------------------------------------------------------------ #
        # Step 2 — Pre-warm model singleton (no-op if already loaded)        #
        # ------------------------------------------------------------------ #
        load_models(self.device)

        # ------------------------------------------------------------------ #
        # Monkey-patch: intercept run_inference milestones                   #
        # We call run_inference() as a black box but need progress updates   #
        # at two internal points. We achieve this by wrapping the two        #
        # internal callables through a lightweight hook mechanism.           #
        # ------------------------------------------------------------------ #
        import inference as _inf_module

        # Save originals
        _orig_scalar_field_to_mesh = _inf_module.scalar_field_to_mesh
        _orig_scalar_field_to_voxel_mesh = _inf_module.scalar_field_to_voxel_mesh

        task_self = self   # closure reference

        def _hooked_progress_wrapper(original_fn, stage_name):
            def wrapper(*args, **kwargs):
                task_self.update_state(
                    state="PROGRESS",
                    meta={
                        "progress":  30,
                        "stage":     f"Forward pass complete — running {stage_name}",
                        "job_id":    job_id,
                    },
                )
                result = original_fn(*args, **kwargs)
                task_self.update_state(
                    state="PROGRESS",
                    meta={
                        "progress":  80,
                        "stage":     f"{stage_name} complete — writing Asset",
                        "job_id":    job_id,
                    },
                )
                return result
            return wrapper

        # Temporarily patch the module-level functions
        _inf_module.scalar_field_to_mesh = _hooked_progress_wrapper(_orig_scalar_field_to_mesh, "Marching Cubes")
        _inf_module.scalar_field_to_voxel_mesh = _hooked_progress_wrapper(_orig_scalar_field_to_voxel_mesh, "Voxel Mesh Gen")

        try:
            result = run_inference(
                job_id=job_id,
                input_tensor=input_tensor,
                noise_vector=noise_vector,
                mc_resolution=mc_resolution,
                export_format=export_format,
                skin_removal_layers=skin_removal_layers
            )
        finally:
            # Always restore originals — critical for singleton reuse
            _inf_module.scalar_field_to_mesh = _orig_scalar_field_to_mesh
            _inf_module.scalar_field_to_voxel_mesh = _orig_scalar_field_to_voxel_mesh

        # ------------------------------------------------------------------ #
        # MILESTONE 3 — COMPLETED                                            #
        # Celery automatically transitions to SUCCESS on clean return.       #
        # We store enriched metadata in Redis for FastAPI to read.           #
        # ------------------------------------------------------------------ #
        wall_elapsed = time.perf_counter() - wall_start
        _write_meta(
            job_id,
            completed_at=time.time(),
            latency_seconds=round(wall_elapsed, 3),
            asset_url=result["asset_url"],
            voxel_grid_url=result.get("voxel_grid_url"),
            voxel_vis_url=result.get("voxel_vis_url"),
            radiography_url=result.get("radiography_url"),
            file_size_bytes=result["file_size_bytes"],
        )

        logger.info(
            "generate_3d_asset COMPLETED | job=%s | latency=%.2fs | asset=%s",
            job_id, wall_elapsed, result["asset_url"],
        )

        # Return value is stored verbatim in the Celery result backend
        # and retrieved by FastAPI via AsyncResult(job_id).result
        return result

    # ---------------------------------------------------------------------- #
    # Exception handling — map to structured error codes                     #
    # ---------------------------------------------------------------------- #
    except SoftTimeLimitExceeded:
        # Task exceeded 100s soft limit — triggered by Celery automatically
        logger.error(
            "generate_3d_asset TIMEOUT | job=%s | elapsed=%.2fs",
            job_id, time.perf_counter() - wall_start,
        )
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            logger.warning("SoftTimeLimitExceeded: VRAM cache cleared for job %s", job_id)

        error_payload = {
            "code":    "INFERENCE_TIMEOUT",
            "message": f"Task exceeded soft time limit of 100s. "
                       f"Elapsed: {time.perf_counter() - wall_start:.1f}s.",
        }
        _write_meta(job_id, failed_at=time.time(), error=error_payload)

        # Re-raise so Celery marks the task FAILURE in the result backend
        raise

    except torch.cuda.OutOfMemoryError as exc:
        logger.error("generate_3d_asset OOM | job=%s", job_id, exc_info=True)
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        error_payload = _build_error_payload(exc)
        _write_meta(job_id, failed_at=time.time(), error=error_payload)
        raise RuntimeError(f"OOM_ERROR: {exc}") from exc

    except Exception as exc:
        logger.error(
            "generate_3d_asset FAILED | job=%s | error=%s",
            job_id, exc, exc_info=True,
        )
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        error_payload = _build_error_payload(exc)
        _write_meta(job_id, failed_at=time.time(), error=error_payload)
        raise


# --------------------------------------------------------------------------- #
# TTL Purge Task — Celery Beat, runs every hour                               #
# --------------------------------------------------------------------------- #
@celery_app.task(
    name="tasks.purge_expired_assets",
    queue="gan3d.generate",
    ignore_result=True,
)
def purge_expired_assets() -> None:
    """
    Scan Redis for job metadata keys older than 24 hours.
    For each expired job:
      1. Delete the physical .glb file from OUTPUTS_DIR.
      2. Mark the Celery result backend entry as EXPIRED.
      3. Delete the gan3d:job:<id>:meta hash.

    Runs on the top of every hour via Celery Beat (configured in celery_app.py).
    Designed to be idempotent — safe to run multiple times for the same job.
    """
    TTL_SECONDS = 86400  # 24 hours
    now         = time.time()
    purged      = 0
    errors      = 0

    logger.info("purge_expired_assets: scanning Redis for expired jobs...")

    # Scan all gan3d:job:*:meta keys — SCAN is non-blocking unlike KEYS
    cursor = 0
    pattern = "gan3d:job:*:meta"

    while True:
        cursor, keys = redis_client.scan(cursor=cursor, match=pattern, count=100)

        for key in keys:
            try:
                raw = redis_client.hgetall(key)
                if not raw:
                    continue

                meta = {k: json.loads(v) for k, v in raw.items()}
                submitted_at = meta.get("submitted_at")

                if submitted_at is None:
                    continue

                age_seconds = now - float(submitted_at)
                if age_seconds < TTL_SECONDS:
                    continue

                # Extract job_id from key pattern: gan3d:job:<job_id>:meta
                parts  = key.split(":")
                job_id = parts[2] if len(parts) >= 4 else None

                if not job_id:
                    continue

                # --- 1. Delete physical .glb file ---------------------------
                glb_path = OUTPUTS_DIR / f"{job_id}.glb"
                if glb_path.exists():
                    glb_path.unlink()
                    logger.info(
                        "purge_expired_assets: deleted %s (age=%.1fh)",
                        glb_path, age_seconds / 3600,
                    )
                else:
                    logger.debug(
                        "purge_expired_assets: GLB not found (already purged?): %s",
                        glb_path,
                    )

                # --- 2. Mark Celery result as EXPIRED -----------------------
                # We write directly to the result backend key so FastAPI's
                # AsyncResult(job_id).state returns "EXPIRED" correctly.
                from celery.backends.base import DisabledBackend
                backend = celery_app.backend
                if not isinstance(backend, DisabledBackend):
                    backend.store_result(
                        job_id,
                        result={"code": "EXPIRED", "message": "Asset TTL exceeded 24h."},
                        state="EXPIRED",
                    )

                # --- 3. Delete the metadata hash ----------------------------
                redis_client.delete(key)
                logger.info("purge_expired_assets: purged job %s", job_id)
                purged += 1

            except Exception as exc:
                logger.error(
                    "purge_expired_assets: error processing key %s: %s", key, exc
                )
                errors += 1

        if cursor == 0:
            break  # SCAN complete

    logger.info(
        "purge_expired_assets: complete. purged=%d errors=%d", purged, errors
    )
